version: '2.1'
services:
    nginx:
        image: sproutstack/nginx
        container_name: ss_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./workspace:/workspace
            - ./logs/nginx:/var/log/nginx/
            - ./nginx/sites/:/etc/nginx/sites/
            - ./nginx/templates/:/etc/nginx/templates/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/ports.nginx:/etc/nginx/ports.nginx
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
        networks:
            - server
        depends_on:
            - phpfpm56
            - phpfpm70
            - phpfpm71
            - phpfpm72
        command: /bin/ash -c "(adduser -D -H -u ${USERID:-1000} www-data || true) >/dev/null && exec nginx -g 'daemon off;'"
    varnish:
        image: sproutstack/varnish
        container_name: ss_varnish
        ports:
            - "8888:8888"
        volumes:
            - ./varnish/default.vcl:/etc/varnish/default.vcl
            - ./logs/varnish:/var/log/varnish
        networks:
            - server
        depends_on:
            - nginx
    phpfpm56:
        image: sproutstack/phpfpm:5.6
        container_name: ss_phpfpm5.6
        user: '${USERID:-1000}:${GROUPID:-1000}'
        cap_add:
            - SYS_PTRACE
        volumes:
            - ./workspace:/workspace
            - ./logs/phpfpm56:/var/log/php-fpm
            - ./php/5.6/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/5.6/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - /etc/passwd:/etc/passwd:ro
        networks:
            - server
            - database
    phpfpm70:
        image: sproutstack/phpfpm:7.0
        container_name: ss_phpfpm7.0
        user: '${USERID:-1000}:${GROUPID:-1000}'
        cap_add:
            - SYS_PTRACE
        volumes:
            - ./workspace:/workspace
            - ./logs/phpfpm70:/var/log/php-fpm
            - ./php/7.0/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/7.0/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - /etc/passwd:/etc/passwd:ro
        networks:
            - server
            - database
    phpfpm71:
        image: sproutstack/phpfpm:7.1
        container_name: ss_phpfpm7.1
        user: '${USERID:-1000}:${GROUPID:-1000}'
        cap_add:
            - SYS_PTRACE
        volumes:
            - ./workspace:/workspace
            - ./logs/phpfpm71:/var/log/php-fpm
            - ./php/7.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/7.1/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - /etc/passwd:/etc/passwd:ro
        networks:
            - server
            - database
    phpfpm72:
        image: sproutstack/phpfpm:7.2
        container_name: ss_phpfpm7.2
        user: '${USERID:-1000}:${GROUPID:-1000}'
        cap_add:
            - SYS_PTRACE
        volumes:
            - ./workspace:/workspace
            - ./logs/phpfpm72:/var/log/php-fpm
            - ./php/7.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/7.2/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - /etc/passwd:/etc/passwd:ro
        networks:
            - server
            - database
    phpfpm73:
        image: sproutstack/phpfpm:7.3
        container_name: ss_phpfpm7.3
        user: '${USERID:-1000}:${GROUPID:-1000}'
        cap_add:
            - SYS_PTRACE
        volumes:
            - ./workspace:/workspace
            - ./logs/phpfpm73:/var/log/php-fpm
            - ./php/7.3/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/7.3/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - /etc/passwd:/etc/passwd:ro
        networks:
            - server
            - database
    mysql:
        image: mysql:5.7
        container_name: ss_mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - database
    redis:
        image: redis:alpine
        container_name: ss_redis
        ports:
            - "6379:6379"
        networks:
            - database
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ss_phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
        networks:
            - database
    mailhog:
        image: mailhog/mailhog
        container_name: ss_mailhog
        ports:
            - "25:1025"
            - "8025:8025"
volumes:
    mysql:
networks:
    server:
    database: